;;(global-set-key (kbd "C-c n l") 'org-roam-buffer-toggle)
;; (global-set-key (kbd "C-c n f") 'org-roam-node-find)
;; (global-set-key (kbd "C-c n g") 'org-roam-graph)
;; (global-set-key (kbd "C-c n i") 'org-roam-node-insert)
;; (global-set-key (kbd "C-c n c") 'org-roam-capture)
;; (global-set-key (kbd "C-x t t") 'treemacs)
;; (global-set-key (kbd "C-x t C-t") 'treemacs-find-tag)
(global-set-key (kbd "M-i") 'previous-line)
(global-set-key (kbd "M-I") 'scroll-down-command)
(global-set-key (kbd "M-k") 'next-line)
(global-set-key (kbd "M-K") 'scroll-up-command)
(global-set-key (kbd "M-j") 'backward-char)
(global-set-key (kbd "M-J") 'move-beginning-of-line)
(global-set-key (kbd "M-l") 'forward-char)
(global-set-key (kbd "M-L") 'move-end-of-line)
(global-set-key (kbd "M-o") 'forward-word)
(global-set-key (kbd "M-O") 'forward-paragraph)
(global-set-key (kbd "M-u") 'backward-word)
(global-set-key (kbd "M-U") 'backward-paragraph)
(global-set-key (kbd "C-f") 'isearch-forward)
(global-set-key (kbd "M-K") 'kill-sentence)
(define-key selectrum-minibuffer-map [remap backward-char] 'selectrum-backward-kill-sexp)
(define-key selectrum-minibuffer-map (kbd "<left>") 'selectrum-backward-kill-sexp)
(define-key selectrum-minibuffer-map [remap forward-char] 'selectrum-insert-current-candidate)
(define-key selectrum-minibuffer-map (kbd "<right>") 'selectrum-insert-current-candidate)
(define-key selectrum-minibuffer-map [remap previous-line] 'selectrum-previous-candidate)
(define-key selectrum-minibuffer-map (kbd "M-o") 'selectrum-quick-insert)

(provide 'keymaps)


